food_card/urls.py
from django.urls import path
from food_card.views import index, recipe


urlpatterns = [
    path("", index, name='index'),
    path("recipe<int:id>/", recipe, name='recipe')
]

foodplan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('food_card.urls')),
    path("recipe<int:id>/", include('food_card.urls')),
    path('', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import login, lk, registration, logout, create_order

app_name = 'users'

urlpatterns = [
    path("login/", login, name='login'),
    path('lk/', lk, name='lk'),
    path('registration/', registration, name='registration'),
    path('logout/', logout, name='logout'),
    path('create_order/', create_order, name='create_order')
]

food_card/models.py
from django.db import models


class Recipe(models.Model):
    title = models.CharField(
        'Название',
        max_length=300,
        db_index=True
    )
    recipe_items = models.ManyToManyField(
        'RecipeItems',
        related_name='recipes'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Рецепты'
        verbose_name = 'Рецепт'


class RecipeItems(models.Model):
    product = models.ForeignKey(
        'Product',
        related_name='in_recipe_items',
        on_delete=models.CASCADE
    )
    quantity = models.PositiveIntegerField('Количество (грамм)')

    def __str__(self):
        return f'{self.product} ({self.quantity}г.)'

    class Meta:
        verbose_name_plural = 'Ингредиенты'
        verbose_name = 'Ингредиент'


class Product(models.Model):
    title = models.CharField(
        'Название',
        max_length=200,
        db_index=True
    )
    calories = models.PositiveIntegerField('Калорийность (на 100г.)')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name_plural = 'Продукты'
        verbose_name = 'Продукт'

food_card/views.py
from django.shortcuts import render, get_object_or_404
from .models import Recipe


def index(request):
    context = {
        'title': 'План питания на неделю, меню, рецепты, список покупок. Классическое меню, безуглеводное меню'
    }
    return render(request, 'food_card/index.html', context)


def recipe(request, id):
    recipe = get_object_or_404(Recipe.objects.prefetch_related('recipe_items', 'recipe_items__product'), id=id)
    recipe_details = {
        'title': recipe.title,
        'products': {}
    }
    calories = 0

    for recipe_item in recipe.recipe_items.all():
        recipe_details['products'].update({f'{recipe_item.product}': recipe_item.quantity})
        calories += (recipe_item.product.calories / 100) * recipe_item.quantity
    recipe_details['calories'] = calories

    return render(
        request,
        template_name=f'food_card/recipe.html',
        context={
            'title': 'План питания на неделю, меню, рецепты, список покупок. Классическое меню, безуглеводное меню',
            'recipe_details': recipe_details
        }
    )

food_card/templates/food_card/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{{ title }}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}">
                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <a class="navbar-brand" href="{% url 'users:login' %}">
                <button class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Войти</button>
                    </a>
            </div>
        </nav>
    </header>
    {% block main %} {% endblock %}
    {% block footer %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

food_card/templates/food_card/recipe.html
{% extends 'food_card/base.html' %}
{% load static %}

{% block main %}
    <main style="margin-top: calc(2rem + 75px);">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-4 d-flex justify-content-center">
                        <div class="card foodplan__card_borderless">
                            <img src="{% static 'img/circle1.png' %}" alt="">
                        </div>
                    </div>
                    <div class="col-12 col-md-6 d-flex flex-column justify-content-between">
                        <h2>{{ recipe_details.title }}</h2>
                        <ul class="list-group list-group-flush">
                            {% for product, quantity in recipe_details.products.items %}
                                <li class="list-group-item">{{ product }} ({{ quantity }}г.)</li>
                            {% endfor %}
                        </ul>
                        <h6>Общая калорийность: {{ recipe_details.calories }} ккал</h6>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}
{% block footer %}
    <footer>
        <nav class="navbar navbar-expand-md navbar-light mt-5">
            <div class="container p-2">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <div class="footer__sideBtns d-flex">
                    <a href="#">
                        <img src="{% static 'img/vk.png' %}" height="38" width="auto" alt="">
                    </a>
                </div>
            </div>
        </nav>
    </footer>
    <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-center mb-2">
            <small class="text-center">
                <h6>© Девман2022. Все права защищены. © Devman2022. All right reserved.</h6>
                <a href="#" class="link-secondary">Политика конфиденциальности</a>
            </small>
        </div>
    </footer>
{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>