foodplan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('food_card.urls')),
    path("recipe<int:id>/", include('food_card.urls')),
    path('', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import login, lk, registration, logout, create_order

app_name = 'users'

urlpatterns = [
    path("login/", login, name='login'),
    path('lk/', lk, name='lk'),
    path('registration/', registration, name='registration'),
    path('logout/', logout, name='logout'),
    path('create_order/', create_order, name='create_order')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)


class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    duration = models.CharField(max_length=128, verbose_name='Срок')
    breakfast = models.CharField(max_length=128, verbose_name='Завтраки')
    lunches = models.CharField(max_length=128, verbose_name='Обеды')
    dinner = models.CharField(max_length=128, verbose_name='Ужины')
    dessert = models.CharField(max_length=128, verbose_name='Десерты')
    quantity = models.CharField(max_length=128, verbose_name='Кол-во персон')
    allergies = models.CharField(max_length=128, verbose_name='Аллергии', null=True, blank=True)

    def __str__(self):
        return f'Подписка для {self.user.username}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from users.models import User, Order


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserLkForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}), required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'image')


# class OrderForm(forms.Form):
#     duration = forms.ModelChoiceField(queryset=Order.objects, label='Срок', widget=forms.Select(attrs={'class': 'form-select'}))
#     breakfast = forms.ModelChoiceField(queryset=Order.objects, label='Завтраки', widget=forms.Select(attrs={'class': 'form-select'}))
#     lunches = forms.ModelChoiceField(queryset=Order.objects, label='Обеды', widget=forms.Select(attrs={'class': 'form-select'}))
#     dinner = forms.ModelChoiceField(queryset=Order.objects, label='Ужины', widget=forms.Select(attrs={'class': 'form-select'}))
#     dessert = forms.ModelChoiceField(queryset=Order.objects, label='Десерты', widget=forms.Select(attrs={'class': 'form-select'}))
#     quantity = forms.ModelChoiceField(queryset=Order.objects, label='Кол-во персон', widget=forms.Select(attrs={'class': 'form-select'}))
#     allergies = forms.ModelChoiceField(queryset=Order.objects, label='Аллергии', widget=forms.CheckboxInput(attrs={'class': 'form-select'}))
#
#     class Meta:
#         model = Order
#         fields = ('duration', 'breakfast', 'lunches', 'dinner', 'dessert', 'quantity', 'allergies')

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from users.forms import UserLoginForm, UserRegistrationForm, UserLkForm
from django.contrib import auth
from django.urls import reverse
from users.models import Order, User


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('users:lk'))
    else:
        form = UserLoginForm()
    context = {
        'title': 'Foodplan 2021 - Меню на неделю FOODPLAN',
        'form': form
    }
    return render(request, 'users/login.html', context)


def lk(request):
    data = Order.objects.all()
    if request.method == 'POST':
        form = UserLkForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:lk'))
    else:
        form = UserLkForm(instance=request.user)
    context = {
        'title': 'Foodplan 2021 - Меню на неделю FOODPLAN',
        'form': form,
        'username': request.user.username,
        'lk': Order.objects.filter(user=request.user)
    }
    return render(request, 'users/lk.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {
        'title': 'Foodplan 2021 - Меню на неделю FOODPLAN',
        'form': form,

    }
    return render(request, 'users/registration.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def create_order(request):
    if request.method == "POST":
        Order.objects.create(
            user=request.user,
            duration=request.POST.get("duration"),
            breakfast=request.POST.get("breakfast"),
            lunches=request.POST.get("lunches"),
            dinner=request.POST.get("dinner"),
            dessert=request.POST.get("dessert"),
            quantity=request.POST.get("quantity"),
            allergies=request.POST.get("allergies1"),
        )
        return HttpResponseRedirect(reverse('index'))

    return render(request, 'users/order.html')


# def order_add(request, order_id):
#     order = Order.objects.get(id=order_id)
#     lk = Order.objects.filter(user=request.user)

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{{ title }}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}">
                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse1"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>

                </button>
                {% if user.is_authenticated %}
                    <ul class="navbar-nav w-100">
                        <li class="nav-item align-items-center d-md-flex flex-grow-1 justify-content-end">
                            <a class="navbar-brand" href="{% url 'users:create_order' %}">
                            <button class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green">Подписка</button>
                                </a>
                        {% else %}
                            <a class="navbar-brand" href="{% url 'users:login' %}">
                            <button class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green">Войти</button>
                                </a>
                        </li>

                    </ul>
                {% endif %}
                </div>
            </div>
        </nav>
    </header>
{% block main %} {% endblock %}
    <footer>
        <nav class="navbar navbar-expand-md navbar-light mt-5">
            <div class="container p-2">
                <a class="navbar-brand" href="{% url 'index' %}">
                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                <div class="footer__sideBtns d-flex">
                    <a href="https://vk.com/gim222606304?sel=c1">
                        <img src="{% static 'img/vk.png' %}" height="38" width="auto" alt="">
                    </a>
                </div>
            </div>
        </nav>
    </footer>
    <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-center mb-2">
            <small class="text-center">
                <h6>© Девман2023. Все права защищены. © Devman2023. All right reserved.</h6>
                <a href="https://policies.google.com/privacy?hl=ru" class="link-secondary">Политика конфиденциальности</a>
            </small>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/lk.html
{% extends 'users/base.html' %}
{% load static %}

{% block main %}
    <main style="margin-top: calc(2rem + 85px);">
        <section>
            <div class="container">
                <div class="row">
                    <div class="card col-12 p-3 mb-5 foodplan__shadow">
                        <h4 class="foodplan__backButton">
                            <strong><small><a href="#" class="link-secondary fw-light"></a></small></strong>
                        </h4>
                        <h2 class="text-center"><strong>Личный кабинет</strong></h2>
                    </div>

                    <div class="card col-12 col-md-2 p-3 mb-3 d-flex flex-column align-items-center foodplan__shadow">
                        <div class="position-relative">
                            <img src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'img/test_avatar.png' %} {% endif %}" alt="" width="100" height="100" class="rounded-pill">
{#                            <span class="badge rounded-circle position-absolute bottom-0 end-0 foodplan__bg_green avatar__plus"><a href="#"#}
{#                                    class="link-dark text-decoration-none align-middle">+</a></span>#}
                        </div>
                        <h3 class="card-title text-center">{{ username }}</h3>
                        <a class="navbar-brand" href="{% url 'users:logout' %}">
                            <button class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green">Выйти</button>
                                </a>
                    </div>

                    <div class="card col-12 col-md-10 p-3 mb-3 foodplan__shadow">
                            <ul class="nav nav-tabs">
                                <li class="nav-item foodplan__tab-item">
                                    <button id="tab1" class="btn shadow-none foodplan__tab-button active" data-bs-toggle="tab" data-bs-target="#data">Персональные данные</button>
                                </li>
                                <li class="nav-item foodplan__tab-item">
                                    <button id="tab2" class="btn shadow-none foodplan__tab-button" data-bs-toggle="tab" data-bs-target="#menu">Моё меню</button>
                                </li>
                                <li class="nav-item foodplan__tab-item flex-grow-1"></li>
                            </ul>
                            <div class="tab-content mt-2">
                                <div class="tab-pane fade show active" id="data">
                                    <form action="{% url 'users:lk' %}" method="post" enctype="multipart/form-data">
                                        {% csrf_token %}

                                        <div class="mb-3">
                                            <div class="d-flex align-items-center justify-content-between">
                                                <label for="{{ form.username.id_for_label }}" class="form-label">Имя</label>
{#                                                <small><a href="#" class="link-dark foodplan_green">изменить</a></small>#}
                                            </div>

                                            {{ form.username }}
                                        </div>
                                        <div class="mb-3">
                                            <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
                                            {{ form.email }}
                                        </div>
                                        <div class="mb-3">
                                            <label for="{{ form.image.id_for_label }}" class="form-label">Выберите изображение</label>
                                            {{ form.image }}
                                        </div>
                                        <div class="mb-3">
                                            <div class="d-flex align-items-center justify-content-between">
                                                <label for="{{ form.password1.id_for_label }}" class="form-label">Пароль</label>
{#                                                <small><a href="#" class="link-dark foodplan_green">изменить</a></small>#}
                                            </div>

                                            {{ form.password1 }}
                                        </div>
                                        <div class="mb-3">
                                            <label for="{{ form.password2.id_for_label }}" class="form-label">Подтверждение пароля</label>
                                            {{ form.password2 }}
                                        </div>
                                        <div class="d-block">
                                            <button type="submit" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Сохранить
                                                изменения</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="tab-pane fade" id="menu">

                                    {% if lk %}
                                    <div class="row">
                                        <div class="col-2">
                                            <img src="{% static 'img/circle1.png' %}" alt="" class="w-100">
                                        </div>
                                        <div class="col-10 col-md-10">
                                            <div class="row">
                                                <div class="col-12">
                                                    <h2>Название подписки</h2>
                                                </div>
                                                <div class="col-md-12 col-lg-9">
                                                    <h6>Описание подписки Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eius saepe ea nobis necessitatibus
                                                        consectetur rem! Eligendi assumenda facere sint quibusdam dolorem quasi doloribus nemo, temporibus molestiae
                                                        distinctio cum laboriosam sed. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eius saepe ea nobis
                                                        necessitatibus consectetur rem! Eligendi
                                                        assumenda facere sint quibusdam dolorem quasi doloribus nemo, temporibus molestiae distinctio cum laboriosam
                                                        sed.</h6>
                                                </div>
                                                <div class="col-md-12 col-lg-3 text-muted d-flex flex-column justify-content-between">
                                                    <div class="d-flex flex-row justify-content-between">
                                                        <small>Персоны: </small><small>3</small>
                                                    </div>
                                                    <div class="d-flex flex-row justify-content-between">
                                                        <small>Аллергии: </small><small>нет</small>
                                                    </div>
                                                    <div class="d-flex flex-row justify-content-between">
                                                        <small>Калории: </small><small>1400</small>
                                                    </div>
                                                    <div class="d-flex flex-row justify-content-between">
                                                        <small>Кол-во приёмов пищи: </small><small>4</small>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% else %}
                                    <h3>Пока здесь пусто. Оформите подписку</h3>
                                    {% endif %}
                                </div>
                            </div>

                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}

{% block main %}
       <main style="margin-top: calc(2rem + 85px);">
        <section>
            <div class="container">
                <div class="card p-3 mb-5 foodplan__shadow">
                    <a href="{% url 'index' %}" class="link-secondary fw-light foodplan__backButton">
                        <svg xmlns="http://www.w3.org/2000/svg" width="9%" height="9%" fill="currentColor" class="bi bi-arrow-left-circle"
                            viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                        </svg>
                    </a>
                    <h2 class="text-center"><strong>Авторизация</strong></h2>
                </div>
                <div class="card px-5 py-3 d-flex align-items-center foodplan__shadow">
                    <form action="{% url 'users:login' %}" method="post">
                        {% csrf_token %}

                        <h1 class="mb-4 text-center"><strong>Вход</strong></h1>
                        <div class="mb-3">
                            <label for="{{ form.username.id_for_label }}" class="form-label">Имя</label>
                            {{ form.username }}
                        </div>
                        <div class="mb-3">
                            <div class="d-flex align-items-center justify-content-between">
                                <label for="{{ form.password.id_for_label }}" class="form-label">Пароль</label>
{#                                <small><a href="#" class="link-dark foodplan_green">Забыли пароль?</a></small>#}
                            </div>
                            {{ form.password }}
                        </div>
                        <div class="row mb-3">
                            <div class="col-12 col-sm-6 mt-3">
                                <button type="submit"
                                    class="btn w-100 btn-outline-success shadow-none foodplan_green foodplan__border_green">Войти</button>
                            </div>
                            <div class="col-12 col-sm-6 mt-3 d-flex justify-content-center align-items-center">
                                <small>Нет аккаунта? <a href="{% url 'users:registration' %}" class="link-dark foodplan_green">Зарегистрируйтесь</a></small>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

users/templates/users/registration.html
{% extends 'users/base.html' %}
{% load static %}

{% block main %}
    <main style="margin-top: calc(2rem + 85px);">
        <section>
            <div class="container">
                <div class="card p-3 mb-5 foodplan__shadow">
                    <a href="{% url 'users:login' %}" class="link-secondary fw-light foodplan__backButton">
                        <svg xmlns="http://www.w3.org/2000/svg" width="9%" height="9%" fill="currentColor" class="bi bi-arrow-left-circle"
                            viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                        </svg>
                    </a>
                    <h2 class="text-center"><strong>Авторизация</strong></h2>
                </div>
                <div class="card px-5 py-3 d-flex align-items-center foodplan__shadow">
                    <form action="{% url 'users:registration' %}" method="post">
                        {% csrf_token %}
                        <h1 class="mb-4 text-center"><strong>Регистрация</strong></h1>
                        <div class="mb-3">
                            <label for="{{ form.username.id_for_label }}" class="form-label">Имя</label>
                            {{ form.username }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
                            {{ form.email }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.password1.id_for_label }}" class="form-label">Пароль</label>
                            {{ form.password1 }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.password2.id_for_label }}" class="form-label">Подтверждение пароля</label>
                            {{ form.password2 }}
                        </div>
                        <div class="row mb-3">
                            <div class="col-12 col-sm-6 mt-3">
                                <button type="submit" class="btn  shadow-nonew-100 btn-outline-success foodplan_green foodplan__border_green">Регистрация</button>
                            </div>
                            <div class="col-12 col-sm-6 mt-3 d-flex justify-content-center align-items-center">
                                <small>Уже есть аккаунт? <a href="{% url 'users:login' %}" class="link-dark foodplan_green">Войти</a></small>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </main>
{% endblock %}